package com.jiuxian.demo.module.uc.entity;

import java.util.Date;

public class UcAuth implements java.io.Serializable{
    private static final long serialVersionUID = -8091394793092587970L;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_auth.pkid
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    private Integer pkid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_auth.name
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_auth.tag
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    private String tag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_auth.pid
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_auth.menu
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    private Byte menu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_auth.path
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    private String path;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_auth.icon
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    private String icon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_auth.sort
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    private Float sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_auth.descr
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    private String descr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_auth.add_time
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    private Date addTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_auth.pkid
     *
     * @return the value of uc_auth.pkid
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    public Integer getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_auth.pkid
     *
     * @param pkid the value for uc_auth.pkid
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    public void setPkid(Integer pkid) {
        this.pkid = pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_auth.name
     *
     * @return the value of uc_auth.name
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_auth.name
     *
     * @param name the value for uc_auth.name
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_auth.tag
     *
     * @return the value of uc_auth.tag
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_auth.tag
     *
     * @param tag the value for uc_auth.tag
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    public void setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_auth.pid
     *
     * @return the value of uc_auth.pid
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_auth.pid
     *
     * @param pid the value for uc_auth.pid
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_auth.menu
     *
     * @return the value of uc_auth.menu
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    public Byte getMenu() {
        return menu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_auth.menu
     *
     * @param menu the value for uc_auth.menu
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    public void setMenu(Byte menu) {
        this.menu = menu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_auth.path
     *
     * @return the value of uc_auth.path
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_auth.path
     *
     * @param path the value for uc_auth.path
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_auth.icon
     *
     * @return the value of uc_auth.icon
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_auth.icon
     *
     * @param icon the value for uc_auth.icon
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_auth.sort
     *
     * @return the value of uc_auth.sort
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    public Float getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_auth.sort
     *
     * @param sort the value for uc_auth.sort
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    public void setSort(Float sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_auth.descr
     *
     * @return the value of uc_auth.descr
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    public String getDescr() {
        return descr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_auth.descr
     *
     * @param descr the value for uc_auth.descr
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    public void setDescr(String descr) {
        this.descr = descr == null ? null : descr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_auth.add_time
     *
     * @return the value of uc_auth.add_time
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_auth.add_time
     *
     * @param addTime the value for uc_auth.add_time
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }
}