package com.jiuxian.demo.module.uc.entity;

import java.util.Date;

public class UcLoginRecord implements java.io.Serializable{
    private static final long serialVersionUID = -6487248518887987382L;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_login_record.id
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    private Integer pkid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_login_record.user_pkid
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    private Integer userPkid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_login_record.ip
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_login_record.login_time
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    private Date loginTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_login_record.id
     *
     * @return the value of uc_login_record.id
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    public Integer getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_login_record.id
     *
     * @param pkid the value for uc_login_record.id
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    public void setPkid(Integer pkid) {
        this.pkid = pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_login_record.user_pkid
     *
     * @return the value of uc_login_record.user_pkid
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    public Integer getUserPkid() {
        return userPkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_login_record.user_pkid
     *
     * @param userPkid the value for uc_login_record.user_pkid
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    public void setUserPkid(Integer userPkid) {
        this.userPkid = userPkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_login_record.ip
     *
     * @return the value of uc_login_record.ip
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_login_record.ip
     *
     * @param ip the value for uc_login_record.ip
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_login_record.login_time
     *
     * @return the value of uc_login_record.login_time
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    public Date getLoginTime() {
        return loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_login_record.login_time
     *
     * @param loginTime the value for uc_login_record.login_time
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    public void setLoginTime(Date loginTime) {
        this.loginTime = loginTime;
    }
}