package com.jiuxian.demo.module.uc.entity;

import java.util.Date;

public class UcRoleAuthMap implements java.io.Serializable{
    private static final long serialVersionUID = -2904500922509654397L;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_role_auth_map.pkid
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    private Integer pkid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_role_auth_map.role_pkid
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    private Integer rolePkid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_role_auth_map.auth_pkid
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    private Integer authPkid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_role_auth_map.add_time
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    private Date addTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_role_auth_map.pkid
     *
     * @return the value of uc_role_auth_map.pkid
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    public Integer getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_role_auth_map.pkid
     *
     * @param pkid the value for uc_role_auth_map.pkid
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    public void setPkid(Integer pkid) {
        this.pkid = pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_role_auth_map.role_pkid
     *
     * @return the value of uc_role_auth_map.role_pkid
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    public Integer getRolePkid() {
        return rolePkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_role_auth_map.role_pkid
     *
     * @param rolePkid the value for uc_role_auth_map.role_pkid
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    public void setRolePkid(Integer rolePkid) {
        this.rolePkid = rolePkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_role_auth_map.auth_pkid
     *
     * @return the value of uc_role_auth_map.auth_pkid
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    public Integer getAuthPkid() {
        return authPkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_role_auth_map.auth_pkid
     *
     * @param authPkid the value for uc_role_auth_map.auth_pkid
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    public void setAuthPkid(Integer authPkid) {
        this.authPkid = authPkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_role_auth_map.add_time
     *
     * @return the value of uc_role_auth_map.add_time
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_role_auth_map.add_time
     *
     * @param addTime the value for uc_role_auth_map.add_time
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }
}