package com.jiuxian.demo.module.uc.entity;

import java.util.Date;

public class UcRole implements java.io.Serializable{
    private static final long serialVersionUID = 3420888403321453280L;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_role.pkid
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    private Integer pkid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_role.name
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_role.tag
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    private String tag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_role.add_time
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    private Date addTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_role.pkid
     *
     * @return the value of uc_role.pkid
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    public Integer getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_role.pkid
     *
     * @param pkid the value for uc_role.pkid
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    public void setPkid(Integer pkid) {
        this.pkid = pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_role.name
     *
     * @return the value of uc_role.name
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_role.name
     *
     * @param name the value for uc_role.name
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_role.tag
     *
     * @return the value of uc_role.tag
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_role.tag
     *
     * @param tag the value for uc_role.tag
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    public void setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_role.add_time
     *
     * @return the value of uc_role.add_time
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_role.add_time
     *
     * @param addTime the value for uc_role.add_time
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }
}