package com.jiuxian.demo.module.uc.entity;

import java.util.Date;

public class UcUser implements java.io.Serializable{
    private static final long serialVersionUID = -3959688041453571481L;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user.pkid
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    private Integer pkid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user.name
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user.login_name
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    private String loginName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user.passwd
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    private String passwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user.ticket
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    private String ticket;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user.add_time
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    private Date addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user.email
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user.phone
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    private String phone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user.pkid
     *
     * @return the value of uc_user.pkid
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    public Integer getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user.pkid
     *
     * @param pkid the value for uc_user.pkid
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    public void setPkid(Integer pkid) {
        this.pkid = pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user.name
     *
     * @return the value of uc_user.name
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user.name
     *
     * @param name the value for uc_user.name
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user.login_name
     *
     * @return the value of uc_user.login_name
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user.login_name
     *
     * @param loginName the value for uc_user.login_name
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user.passwd
     *
     * @return the value of uc_user.passwd
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    public String getPasswd() {
        return passwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user.passwd
     *
     * @param passwd the value for uc_user.passwd
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    public void setPasswd(String passwd) {
        this.passwd = passwd == null ? null : passwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user.ticket
     *
     * @return the value of uc_user.ticket
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    public String getTicket() {
        return ticket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user.ticket
     *
     * @param ticket the value for uc_user.ticket
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    public void setTicket(String ticket) {
        this.ticket = ticket == null ? null : ticket.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user.add_time
     *
     * @return the value of uc_user.add_time
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user.add_time
     *
     * @param addTime the value for uc_user.add_time
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user.email
     *
     * @return the value of uc_user.email
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user.email
     *
     * @param email the value for uc_user.email
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user.phone
     *
     * @return the value of uc_user.phone
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user.phone
     *
     * @param phone the value for uc_user.phone
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }
}