package com.jiuxian.demo.module.uc.entity;

import java.util.Date;

public class UcUserRoleMap implements java.io.Serializable{
    private static final long serialVersionUID = 8332913539477393711L;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user_role_map.pkid
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    private Integer pkid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user_role_map.user_pkid
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    private Integer userPkid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user_role_map.role_pkid
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    private Integer rolePkid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user_role_map.allot
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    private Byte allot;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user_role_map.add_time
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    private Date addTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user_role_map.pkid
     *
     * @return the value of uc_user_role_map.pkid
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    public Integer getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user_role_map.pkid
     *
     * @param pkid the value for uc_user_role_map.pkid
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    public void setPkid(Integer pkid) {
        this.pkid = pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user_role_map.user_pkid
     *
     * @return the value of uc_user_role_map.user_pkid
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    public Integer getUserPkid() {
        return userPkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user_role_map.user_pkid
     *
     * @param userPkid the value for uc_user_role_map.user_pkid
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    public void setUserPkid(Integer userPkid) {
        this.userPkid = userPkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user_role_map.role_pkid
     *
     * @return the value of uc_user_role_map.role_pkid
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    public Integer getRolePkid() {
        return rolePkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user_role_map.role_pkid
     *
     * @param rolePkid the value for uc_user_role_map.role_pkid
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    public void setRolePkid(Integer rolePkid) {
        this.rolePkid = rolePkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user_role_map.allot
     *
     * @return the value of uc_user_role_map.allot
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    public Byte getAllot() {
        return allot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user_role_map.allot
     *
     * @param allot the value for uc_user_role_map.allot
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    public void setAllot(Byte allot) {
        this.allot = allot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user_role_map.add_time
     *
     * @return the value of uc_user_role_map.add_time
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user_role_map.add_time
     *
     * @param addTime the value for uc_user_role_map.add_time
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }
}