package com.jiuxian.demo.module.uc.dao;

import com.jiuxian.demo.module.uc.entity.UcRole;
import com.jiuxian.demo.module.uc.entity.UcUserRoleMap;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface UcRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_role
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    int deleteByPrimaryKey(Integer pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_role
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    int insert(UcRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_role
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    int insertSelective(UcRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_role
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    UcRole selectByPrimaryKey(Integer pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_role
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    int updateByPrimaryKeySelective(UcRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_role
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    int updateByPrimaryKey(UcRole record);

    List<UcRole> selectByPrimaryKeys(List<Integer> pkidList);

    int countByProperties(@Param("params") Map<String, Object> properties);

    List<UcRole> findByProperties(@Param("params") Map<String, Object> properties, @Param("startRow") int startRow, @Param("pageSize") int pageSize);
}