package com.jiuxian.demo.module.uc.dao;

import com.jiuxian.demo.module.uc.entity.UcUser;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface UcUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_user
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    int deleteByPrimaryKey(Integer pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_user
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    int insert(UcUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_user
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    int insertSelective(UcUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_user
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    UcUser selectByPrimaryKey(Integer pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_user
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    int updateByPrimaryKeySelective(UcUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_user
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    int updateByPrimaryKey(UcUser record);

    List<UcUser> selectByPrimaryKeys(List<Integer> pkidList);

    int countByProperties(@Param("params") Map<String, Object> properties);

    List<UcUser> findByProperties(@Param("params") Map<String, Object> properties, @Param("startRow") int startRow, @Param("pageSize") int pageSize);
}