package com.jiuxian.demo.module.uc.dao;

import com.jiuxian.demo.module.uc.entity.UcUser;
import com.jiuxian.demo.module.uc.entity.UcUserRoleMap;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface UcUserRoleMapMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_user_role_map
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    int deleteByPrimaryKey(Integer pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_user_role_map
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    int insert(UcUserRoleMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_user_role_map
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    int insertSelective(UcUserRoleMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_user_role_map
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    UcUserRoleMap selectByPrimaryKey(Integer pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_user_role_map
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    int updateByPrimaryKeySelective(UcUserRoleMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_user_role_map
     *
     * @mbg.generated Tue Aug 23 15:48:40 CST 2016
     */
    int updateByPrimaryKey(UcUserRoleMap record);

    List<UcUserRoleMap> selectByPrimaryKeys(List<Integer> pkidList);

    int countByProperties(@Param("params") Map<String, Object> properties);

    List<UcUserRoleMap> findByProperties(@Param("params") Map<String, Object> properties, @Param("startRow") int startRow, @Param("pageSize") int pageSize);
}